### PR TITLE
Documentation Update

### PR DESCRIPTION
**Pull request by matthewspear**
I've done a quick tidy up of the README.md:

- Caught a couple of typos
- Corrected some commands
- Added a clickable contents section
- Added syntax highlighting

I have slightly changed the hierarchy, so let me know what you think!

### CODE REVIEW

**Comment by bbodin** [comment]
Thank you very much ! 
The only thing I am confused about is the "Where are the dataset?" at the end, because it is the first thing to do when you download SLAMBench.

**Comment by matthewspear** [comment]
Did you mean algorithms / usecases?

I was working from the focus of a hierarchy, information architecture and the perspective of someone visiting the GitHub page for the first time having loosely heard of SLAMBench or maybe having read one of the papers.

The first question someone landing on the page will what to know is what am I looking at and is it the right tool for me. So a summary being the first item makes the most sense.

Next if it was what they were looking for, they'd clone and set up SLAMBench. Only once they were at that stage then they would be need to know the usage commands.

I agree it doesn't make sense right at the bottom in FAQs and is pretty important, so maybe moving it into a section slotting it after set up and before run existing algorithms: 

```
* What is SLAMBench?
* How to set up SLAMBench?
> * What algorithms does SLAMBench support?
* How to run an existing algorithm with SLAMBench?
* How to add a new benchmark in SLAMBench?
* Known Issues
* Release History
```

I can take a proper look and re-work it tomorrow!

**Comment by matthewspear** [comment]
I think @mihaibujanca mentioned he might have some changes for this branch too

**Comment by bbodin** [comment]
OK, I like your last plan. In my dev branch I might have documentation stuff to merge eventually, and @jkmingwen might soon integrate some OSX docs as well.

**Comment by matthewspear** [comment]
> OK, I like your last plan. In my dev branch I might have documentation stuff to merge eventually, and @jkmingwen might soon integrate some OSX docs as well.

Excited for the OSX / macOS stuff!!

**Comment by matthewspear** [comment]
@bbodin I think this is all the changes for the PR, can this be merged?

**Comment by bbodin** [comment]
Done! :-)

**Comment by matthewspear** [comment]
Thanks!

**Pull request merged**
